### ISSUE TITLE
Install pYSFReflector on Debian9 where YSFReflector was already running

### ISSUE THREAD

**Issue by iu2kul** [iu5jae/pYSFReflector#22]
Hi there,

I have tryed to upgrade our YSFReflector to pYSFReflector release without succeded.

In few words, I cannot see port 42000 or others open. I follow several time the installation instruction, step by step but with bad result.

WSYSFDashbord is working using standard YSFReflector. 

Where I' m wrong ? Any suggestions / idea ?

Thanks in adavance for any help

73 IU2KUL

**Comment by 9Y4C** [comment]
I don't understand you can't see the ports open, you have to create rule in your firewall to allow port 42000 and any other port

**Comment by iu2kul** [comment]
Look, the reflector is installed on a webserver, all ports are open.
g4klx YSFReflector is already running on port 42000. Installing pYSFReflector, even on another ports, I cannot see the reflector running. I hope I was clear. 73

**Comment by 9Y4C** [comment]
Did you run the command to start the reflector also set it up to run
automatically on start-up?
